### PR TITLE
Optimization attempt #1

### PR DESCRIPTION
**Pull request by C3pa**
Hi!

This is my proposal from #7 in action. I tried running the existing tests in the way you described. I got mixed results so I am not sure if the results are conclusive, so I'd really appreciate it if somebody else also compared the performance before/after these changes.

This is the output of the tests:

Before:
```
测试[ast]...
测试[ast]用时[0.112]
测试[grammar]...
测试[grammar]用时[0.009]
测试[grammar_check]...
测试[grammar_check]用时[0.008]
测试[syntax_check]...
测试[syntax_check]用时[0.008]
测试[perform]...
[test\perform\1.txt]测试完成，大小[42.265]kb，速度[1.854]mb/s，平均用时[22.800]毫秒
[test\perform\2.txt]测试完成，大小[6.595]kb，速度[7.328]mb/s，平均用时[0.900]毫秒
[test\perform\3.txt]测试完成，大小[1.257]kb，速度[0.662]mb/s，平均用时[1.900]毫秒
[test\perform\4.txt]测试完成，大小[4923.960]kb，速度[2.219]mb/s，平均用时[2219.000]毫秒
[test\perform\5.txt]测试完成，大小[1451.154]kb，速度[3.643]mb/s，平均用时[398.333]毫秒
[test\perform\6.txt]测试完成，大小[38.577]kb，速度[2.717]mb/s，平均用时[14.200]毫秒
[test\perform\7.txt]测试完成，大小[52.448]kb，速度[1.609]mb/s，平均用时[32.600]毫秒
综合性能测试完成，总大小[456.419]kb，速度[2.056]mb/s，用时[0.222]秒
测试[perform]用时[4.380]
测试完成
```

After:
```
测试[ast]...
测试[ast]用时[0.144]
测试[grammar]...
测试[grammar]用时[0.008]
测试[grammar_check]...
测试[grammar_check]用时[0.011]
测试[syntax_check]...
测试[syntax_check]用时[0.040]
测试[perform]...
[test\perform\1.txt]测试完成，大小[42.265]kb，速度[1.049]mb/s，平均用时[40.300]毫秒
[test\perform\2.txt]测试完成，大小[6.595]kb，速度[8.244]mb/s，平均用时[0.800]毫秒
[test\perform\3.txt]测试完成，大小[1.257]kb，速度[0.662]mb/s，平均用时[1.900]毫秒
[test\perform\4.txt]测试完成，大小[4923.960]kb，速度[2.452]mb/s，平均用时[2008.000]毫秒
[test\perform\5.txt]测试完成，大小[1451.154]kb，速度[3.502]mb/s，平均用时[414.333]毫秒
[test\perform\6.txt]测试完成，大小[38.577]kb，速度[2.816]mb/s，平均用时[13.700]毫秒
[test\perform\7.txt]测试完成，大小[52.448]kb，速度[1.619]mb/s，平均用时[32.400]毫秒
综合性能测试完成，总大小[456.003]kb，速度[1.869]mb/s，用时[0.244]秒
测试[perform]用时[4.411]
测试完成
```

### CODE REVIEW

**Comment by sumneko** [comment]
All files in the directory `test\perform\` contain no tests about LuaDoc. The result you see is only the random errors.
You should write a test case yourself, and then join it into test.

**Comment by C3pa** [comment]
Do you have the scripts needed to execute the benchmark for the Lua Language Server described [here](https://github.com/sumneko/lua-language-server/wiki/Benchmark)? I think that could give better insight if I opened an existing code base before/after the changes than an artificial test environment.

**Comment by sumneko** [comment]
> Do you have the scripts needed to execute the benchmark for the Lua Language Server described [here](https://github.com/sumneko/lua-language-server/wiki/Benchmark)? I think that could give better insight if I opened an existing code base before/after the changes than an artificial test environment.

No, I just read the log.

**Comment by C3pa** [comment]
I tried looking in the logs, but I couldn't determine anything useful. Do you have an idea how I could benchmark this?

**Comment by sumneko** [comment]
I will write a script for benchmark these days.

**Comment by C3pa** [comment]
Thanks for the benchmark! 

It looks like my try didn't really improve performance at all. I tried for 10 times my branch and master. The difference was negligible or the master even outperformed my changes by a small margin. Because of that, I am closing this.

**Pull request closed without merging**
